---
# Show some output for testing access to nested variables

- name: begin variable fun
  hosts: all
  vars_files:
    - ../vars/proxy_hosts.yml
- name: "Ansible | Print a variable"
  debug:
    msg: "The operating system is {{ ansible_distribution }}"
