---
# Show some output for testing access to nested variables
- hosts: all
  tasks:
     - debug: 
         msg: "Network interfaces assigned to "
     - debug: 
         msg: "Default IPv4 address assign to "
