---
# Show some output for testing access to nested variables

- name: begin variable fun
  hosts: all
  vars_files:
    - ../vars/proxy_hosts.yml

- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

