---
# Show some output for testing access to nested variables

- name: begin variable fun
  hosts: all
  vars_files:
    - ../vars/proxy_hosts.yml

# Print as title
- name: "Something here"
  debug:
    msg: "Dummy message"
