---
# Show some output for testing access to nested variables
- hosts: all
  tasks:
     - include_vars:
         file: ../vars/proxy_hosts.yml
     - debug: 
         msg: Access var "{{ remote_install_path }}"
